// src/main/java/com/commander/aqm/aqm_back_end/service/CsvReportService.java
package com.commander.aqm.aqm_back_end.service;

import com.commander.aqm.aqm_back_end.model.Report;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;

@Service
public class CsvReportService {

    private static final DateTimeFormatter DATE_FORMAT =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    public byte[] generateReportCsv(Report report) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        OutputStreamWriter writer = new OutputStreamWriter(baos, StandardCharsets.UTF_8);

        // Write BOM for Excel UTF-8 compatibility
        writer.write('\uFEFF');

        // Header
        writer.write("Air Quality Report\n");
        writer.write("Report ID," + report.getId() + "\n");
        writer.write("Generated by," + report.getUser().getUsername() + "\n");
        writer.write("Location," + report.getLocation().getName() + "\n");
        writer.write("Period," + formatDate(report.getStartTimestamp()) +
                " - " + formatDate(report.getEndTimestamp()) + "\n");
        writer.write("Generated at," + formatDate(report.getCreatedAt()) + "\n");
        writer.write("\n");

        // Statistics Table
        writer.write("Metric,Value\n");
        writer.write("Average PM2.5," + String.format("%.2f", report.getAvgPm25()) + " µg/m³\n");
        writer.write("Average PM10," + String.format("%.2f", report.getAvgPm10()) + " µg/m³\n");
        writer.write("Average AQI," + String.format("%.0f", report.getAvgAqi()) + "\n");
        writer.write("Maximum AQI," + (report.getMaxAqi() != null ? report.getMaxAqi() : "N/A") + "\n");
        writer.write("Minimum AQI," + (report.getMinAqi() != null ? report.getMinAqi() : "N/A") + "\n");
        writer.write("Good Days," + report.getGoodDays() + "\n");
        writer.write("Moderate Days," + report.getModerateDays() + "\n");
        writer.write("Unhealthy Days," + report.getUnhealthyDays() + "\n");
        writer.write("Total Data Points," + report.getTotalDataPoints() + "\n");

        writer.flush();
        writer.close();
        return baos.toByteArray();
    }

    private String formatDate(java.time.LocalDateTime dateTime) {
        if (dateTime == null) return "N/A";
        return dateTime.format(DATE_FORMAT);
    }
}