// src/main/java/com/commander/aqm/aqm_back_end/service/ExcelReportService.java
package com.commander.aqm.aqm_back_end.service;

import com.commander.aqm.aqm_back_end.model.AirQualityData;
import com.commander.aqm.aqm_back_end.model.Report;
import com.commander.aqm.aqm_back_end.repository.AirQualityDataRepository;
import lombok.RequiredArgsConstructor;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ExcelReportService {

    private final AirQualityDataRepository airRepo;
    private static final DateTimeFormatter DATE_FORMAT =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    public byte[] generateReportExcel(Report report) throws Exception {
        Workbook workbook = new XSSFWorkbook();

        // ✅ Sheet 1: Summary Statistics
        createSummarySheet(workbook, report);

        // ✅ Sheet 2: Daily Data
        createDataSheet(workbook, report);

        // ✅ Sheet 3: Distribution Analysis
        createDistributionSheet(workbook, report);

        // Write to bytes
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        workbook.write(baos);
        workbook.close();
        return baos.toByteArray();
    }

    private void createSummarySheet(Workbook workbook, Report report) {
        Sheet sheet = workbook.createSheet("📊 Summary");

        // Styles
        CellStyle headerStyle = createHeaderStyle(workbook);
        CellStyle dataStyle = createDataStyle(workbook);

        int rowNum = 0;

        // Title
        Row titleRow = sheet.createRow(rowNum++);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("🎄 AIR QUALITY REPORT 🎄");
        titleCell.setCellStyle(createTitleStyle(workbook));
        sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 1));

        rowNum++; // Empty row

        // Report Info
        createRow(sheet, rowNum++, "Report ID", report.getId().toString(), headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Generated by", report.getUser().getUsername(), headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Location", report.getLocation().getName(), headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Period",
                formatDate(report.getStartTimestamp()) + " - " + formatDate(report.getEndTimestamp()),
                headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Generated at", formatDate(report.getCreatedAt()), headerStyle, dataStyle);

        rowNum++; // Empty row

        // Metrics Table
        createRow(sheet, rowNum++, "Metric", "Value", headerStyle, headerStyle);
        createRow(sheet, rowNum++, "Average PM2.5",
                String.format("%.2f µg/m³", report.getAvgPm25()), headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Average PM10",
                String.format("%.2f µg/m³", report.getAvgPm10()), headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Average AQI",
                String.format("%.0f", report.getAvgAqi()), headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Maximum AQI",
                report.getMaxAqi() != null ? report.getMaxAqi().toString() : "N/A",
                headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Minimum AQI",
                report.getMinAqi() != null ? report.getMinAqi().toString() : "N/A",
                headerStyle, dataStyle);

        rowNum++; // Empty row

        // Distribution
        createRow(sheet, rowNum++, "Good Days (AQI ≤ 50)",
                report.getGoodDays() + " days", headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Moderate Days (51-100)",
                report.getModerateDays() + " days", headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Unhealthy Days (> 100)",
                report.getUnhealthyDays() + " days", headerStyle, dataStyle);
        createRow(sheet, rowNum++, "Total Data Points",
                report.getTotalDataPoints().toString(), headerStyle, dataStyle);

        // Auto-size columns
        sheet.autoSizeColumn(0);
        sheet.autoSizeColumn(1);
    }

    private void createDataSheet(Workbook workbook, Report report) {
        Sheet sheet = workbook.createSheet("📈 Daily Data");

        // Get raw data
        List<AirQualityData> data = airRepo.findByLocationIdAndTimestampUtcBetween(
                report.getLocation().getId(),
                report.getStartTimestamp(),
                report.getEndTimestamp()
        );

        CellStyle headerStyle = createHeaderStyle(workbook);
        CellStyle dataStyle = createDataStyle(workbook);

        // Header row
        Row headerRow = sheet.createRow(0);
        String[] headers = {"Date/Time", "PM2.5", "PM10", "NO2", "CO", "O3", "SO2", "AQI", "Category"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }

        // Data rows
        int rowNum = 1;
        for (AirQualityData d : data) {
            Row row = sheet.createRow(rowNum++);

            row.createCell(0).setCellValue(formatDate(d.getTimestampUtc()));
            row.createCell(1).setCellValue(d.getPm25() != null ? d.getPm25() : 0);
            row.createCell(2).setCellValue(d.getPm10() != null ? d.getPm10() : 0);
            row.createCell(3).setCellValue(d.getNO2() != null ? d.getNO2() : 0);
            row.createCell(4).setCellValue(d.getCo() != null ? d.getCo() : 0);
            row.createCell(5).setCellValue(d.getO3() != null ? d.getO3() : 0);
            row.createCell(6).setCellValue(d.getSo2() != null ? d.getSo2() : 0);
            row.createCell(7).setCellValue(d.getAqi() != null ? d.getAqi() : 0);
            row.createCell(8).setCellValue(getAqiCategory(d.getAqi()));

            // Apply style
            for (int i = 0; i < headers.length; i++) {
                row.getCell(i).setCellStyle(dataStyle);
            }
        }

        // Auto-size columns
        for (int i = 0; i < headers.length; i++) {
            sheet.autoSizeColumn(i);
        }
    }

    private void createDistributionSheet(Workbook workbook, Report report) {
        Sheet sheet = workbook.createSheet("📊 Distribution");

        CellStyle headerStyle = createHeaderStyle(workbook);
        CellStyle goodStyle = createColoredStyle(workbook, IndexedColors.GREEN);
        CellStyle moderateStyle = createColoredStyle(workbook, IndexedColors.YELLOW);
        CellStyle unhealthyStyle = createColoredStyle(workbook, IndexedColors.RED);

        int rowNum = 0;

        // Title
        Row titleRow = sheet.createRow(rowNum++);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("Air Quality Distribution Analysis");
        titleCell.setCellStyle(createTitleStyle(workbook));
        sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 2));

        rowNum++; // Empty row

        // Header
        Row headerRow = sheet.createRow(rowNum++);
        headerRow.createCell(0).setCellValue("Category");
        headerRow.createCell(1).setCellValue("Days");
        headerRow.createCell(2).setCellValue("Percentage");
        for (int i = 0; i < 3; i++) {
            headerRow.getCell(i).setCellStyle(headerStyle);
        }

        // Calculate total
        int totalDays = report.getGoodDays() + report.getModerateDays() + report.getUnhealthyDays();

        // Good days
        Row goodRow = sheet.createRow(rowNum++);
        goodRow.createCell(0).setCellValue("😊 Good (AQI ≤ 50)");
        goodRow.createCell(1).setCellValue(report.getGoodDays());
        goodRow.createCell(2).setCellValue(String.format("%.1f%%",
                (report.getGoodDays() * 100.0 / totalDays)));
        for (int i = 0; i < 3; i++) {
            goodRow.getCell(i).setCellStyle(goodStyle);
        }

        // Moderate days
        Row moderateRow = sheet.createRow(rowNum++);
        moderateRow.createCell(0).setCellValue("😐 Moderate (51-100)");
        moderateRow.createCell(1).setCellValue(report.getModerateDays());
        moderateRow.createCell(2).setCellValue(String.format("%.1f%%",
                (report.getModerateDays() * 100.0 / totalDays)));
        for (int i = 0; i < 3; i++) {
            moderateRow.getCell(i).setCellStyle(moderateStyle);
        }

        // Unhealthy days
        Row unhealthyRow = sheet.createRow(rowNum++);
        unhealthyRow.createCell(0).setCellValue("😷 Unhealthy (> 100)");
        unhealthyRow.createCell(1).setCellValue(report.getUnhealthyDays());
        unhealthyRow.createCell(2).setCellValue(String.format("%.1f%%",
                (report.getUnhealthyDays() * 100.0 / totalDays)));
        for (int i = 0; i < 3; i++) {
            unhealthyRow.getCell(i).setCellStyle(unhealthyStyle);
        }

        // Auto-size columns
        for (int i = 0; i < 3; i++) {
            sheet.autoSizeColumn(i);
        }
    }

    // ===== HELPER METHODS =====

    private void createRow(Sheet sheet, int rowNum, String label, String value,
                           CellStyle labelStyle, CellStyle valueStyle) {
        Row row = sheet.createRow(rowNum);
        Cell labelCell = row.createCell(0);
        labelCell.setCellValue(label);
        labelCell.setCellStyle(labelStyle);

        Cell valueCell = row.createCell(1);
        valueCell.setCellValue(value);
        valueCell.setCellStyle(valueStyle);
    }

    private CellStyle createTitleStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        font.setColor(IndexedColors.DARK_BLUE.getIndex());
        style.setFont(font);
        style.setAlignment(HorizontalAlignment.CENTER);
        return style;
    }

    private CellStyle createHeaderStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle createDataStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle createColoredStyle(Workbook workbook, IndexedColors color) {
        CellStyle style = createDataStyle(workbook);
        style.setFillForegroundColor(color.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        return style;
    }

    private String formatDate(java.time.LocalDateTime dateTime) {
        if (dateTime == null) return "N/A";
        return dateTime.format(DATE_FORMAT);
    }

    private String getAqiCategory(Integer aqi) {
        if (aqi == null) return "Unknown";
        if (aqi <= 50) return "Good";
        if (aqi <= 100) return "Moderate";
        if (aqi <= 150) return "Unhealthy for Sensitive";
        if (aqi <= 200) return "Unhealthy";
        if (aqi <= 300) return "Very Unhealthy";
        return "Hazardous";
    }
}