// src/main/java/com/commander/aqm/aqm_back_end/service/PdfReportService.java
package com.commander.aqm.aqm_back_end.service;

import com.commander.aqm.aqm_back_end.model.Report;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfReportService {

    public byte[] generateReportPdf(Report report) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc);

        // Title
        Paragraph title = new Paragraph("🎄 AIR QUALITY REPORT 🎄")
                .setFontSize(20)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER);
        document.add(title);

        // Report Info
        document.add(new Paragraph("Report ID: " + report.getId()));
        document.add(new Paragraph("Generated by: " + report.getUser().getUsername()));
        document.add(new Paragraph("Location: " + report.getLocation().getName()));
        document.add(new Paragraph("Period: " +
                formatDate(report.getStartTimestamp()) + " - " +
                formatDate(report.getEndTimestamp())));
        document.add(new Paragraph("Generated at: " + formatDate(report.getCreatedAt())));
        document.add(new Paragraph("\n"));

        // Statistics Table
        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 2}));
        table.setWidth(UnitValue.createPercentValue(100));

        // Header
        table.addHeaderCell("Metric");
        table.addHeaderCell("Value");

        // Data
        table.addCell("Average PM2.5");
        table.addCell(String.format("%.2f µg/m³", report.getAvgPm25()));

        table.addCell("Average PM10");
        table.addCell(String.format("%.2f µg/m³", report.getAvgPm10()));

        table.addCell("Average AQI");
        table.addCell(String.format("%.0f", report.getAvgAqi()));

        table.addCell("Maximum AQI");
        table.addCell(report.getMaxAqi() != null ? report.getMaxAqi().toString() : "N/A");

        table.addCell("Minimum AQI");
        table.addCell(report.getMinAqi() != null ? report.getMinAqi().toString() : "N/A");

        table.addCell("Good Days");
        table.addCell(report.getGoodDays() + " days");

        table.addCell("Moderate Days");
        table.addCell(report.getModerateDays() + " days");

        table.addCell("Unhealthy Days");
        table.addCell(report.getUnhealthyDays() + " days");

        table.addCell("Total Data Points");
        table.addCell(report.getTotalDataPoints().toString());

        document.add(table);

        // Footer
        document.add(new Paragraph("\n\n"));
        document.add(new Paragraph("🎅 North Pole Air Quality Monitoring System 🎄")
                .setTextAlignment(TextAlignment.CENTER)
                .setFontSize(10));

        document.close();
        return baos.toByteArray();
    }

    private String formatDate(java.time.LocalDateTime dateTime) {
        if (dateTime == null) return "N/A";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        return dateTime.format(formatter);
    }
}